# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cs2GG.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_off.setEnabled(False)
        self.radioButton_off.setCheckable(True)
        self.radioButton_off.setChecked(True)
        self.radioButton_off.setObjectName("radioButton_off")
        self.horizontalLayout.addWidget(self.radioButton_off)
        self.radioButton_pistol = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_pistol.setEnabled(False)
        self.radioButton_pistol.setObjectName("radioButton_pistol")
        self.horizontalLayout.addWidget(self.radioButton_pistol)
        self.radioButton_ak = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ak.setEnabled(False)
        self.radioButton_ak.setObjectName("radioButton_ak")
        self.horizontalLayout.addWidget(self.radioButton_ak)
        self.radioButton_a4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_a4.setEnabled(False)
        self.radioButton_a4.setObjectName("radioButton_a4")
        self.horizontalLayout.addWidget(self.radioButton_a4)
        self.radioButton_a1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_a1.setEnabled(False)
        self.radioButton_a1.setObjectName("radioButton_a1")
        self.horizontalLayout.addWidget(self.radioButton_a1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setObjectName("menubar")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setObjectName("menuabout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncs2GunGod = QtWidgets.QAction(MainWindow)
        self.actioncs2GunGod.setObjectName("actioncs2GunGod")
        self.menuabout.addAction(self.actioncs2GunGod)
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_off.setText(_translate("MainWindow", "OFF"))
        self.radioButton_pistol.setText(_translate("MainWindow", "Pistol"))
        self.radioButton_ak.setText(_translate("MainWindow", "AK"))
        self.radioButton_a4.setText(_translate("MainWindow", "A4"))
        self.radioButton_a1.setText(_translate("MainWindow", "A1"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.actioncs2GunGod.setText(_translate("MainWindow", "cs2GunGod"))
